E_Voting/E_Voting/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('ajax/login/', views.LoginViewAjax.as_view(
        template_name='partial_login_ajax.html'),
        name='login_ajax'),
    path('ajax/logout/', views.logout_view_ajax, name='logout_ajax'),
    path('registration/',include('registration.urls',namespace='registration')),
    path('election/',include('election.urls',namespace='election')),
    path('reporting/',include('reporting.urls',namespace='reporting')),
    path('accounts/login/', views.LoginView.as_view(),
        name='login'),
    path('test/',
        views.TestPage.as_view(),
        name='test'
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_Voting/election/urls.py
from django.urls import path
from election.viewsF import vote,live_monitoring

app_name = 'election'

urlpatterns = [
    path('ajax/voter/authenticate/', vote.authenticate_voter_ajax,
        name='authenticate_voter_ajax'
    ),
    path('ajax/voter/confirmation/<int:pk>',
        vote.show_voter_confirmation_ajax,
        name='confirm_voter_ajax'
    ),
    path('ajax/voter/ballot/<int:voter_id>',
        vote.show_voter_ballot_ajax,
        name='voter_ballot_ajax'
    ),
    path('liveVoteMonitoring/',
        live_monitoring.ElectionLiveMonitoring.as_view(),
        name='election_live_monitoring'
    ),
    path('ajax/populate_vote_count/',
        live_monitoring.populate_vote_count_ajax,
        name='populate_vote_count_live'
    ),
    path('ajax/check_for_new_vote/',
        live_monitoring.check_for_new_vote_ajax,
        name='check_for_new_vote_ajax'
    ),
    path('ajax/review_voters_vote_auth/',
        vote.review_voters_vote_auth_ajax,
        name='review_voters_vote_auth_ajax'
    ),
    path('ajax/populate_participation_rate_live/',
        live_monitoring.populate_participation_rate_ajax,
        name='election_live_populate_participation_rate'
    ),
    ]

E_Voting/registration/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
from E_Voting import views as MainViews
from registration.viewsF.cbv import (
                    upload_students,update_student,
                    list_student,create_student,delete_student,create_user,
                    list_user,election,position,party,candidate
)
from registration.viewsF.functionBV import update_user

app_name = 'registration'

urlpatterns = [
    path('',MainViews.HomePage.as_view(),name='home'),
    path('uploadstudents/',upload_students.UploadStudents.as_view(),
        name='upload_students'
        ),
    path('uploadstudents2/',upload_students.UploadStudentsAjax.as_view(),
        name='upload_students2'
        ),
    path('uploadstudents/verification/',
        upload_students.UploadStudentsVerification.as_view(),
        name='upload_students_verification'
        ),
    path('students/',list_student.StudentsListView.as_view(),
        name='list_student'
        ),
    url(r'^student/update/(?P<pk>\d+)/',
        update_student.StudentUpdateView.as_view(),
        name='update_student'
        ),
    path('student/add/',create_student.StudentCreate.as_view(),
        name='add_student'
        ),
    url(r'^student/delete/(?P<pk>\d+)/',
        delete_student.StudentDelete.as_view(),
        name='delete_student'
        ),
    path('user/create/', create_user.UserCreate.as_view(mode="create user"),
        name='create_user'
        ),
    path('ajax/user/update/<int:pk>/',
        update_user.update_user_ajax,
        name='update_user_ajax'
        ),
    path('ajax/user/reset_password/<int:pk>/',
        update_user.update_user_reset_password_ajax,
        name='update_user_reset_password_ajax'
        ),
    path('ajax/user/deactivate_activate/<int:pk>/',
        update_user.deactivate_activate_ajax,
        name='deactivate_activate_ajax'
        ),
    path('users/',
        list_user.UserList.as_view(),
        name='list_user'
        ),
    path('ajax/user/create/',
        create_user.create_user_ajax,
        name='create_user_ajax'
        ),
    path('election_officer/create/',
        create_user.UserCreate.as_view(mode="create election officer"),
        name='create_election_officer'
        ),
    path('ajax/validate_username/',
        create_user.validate_username,
        name='validate_username_ajax'),
    path('ajax/get_filter_options_for_level/',
        list_student.get_filter_options_for_level,
        name='get_filter_options_for_level_ajax'
        ),
    path('ajax/populate_table_upladed_students/',
        list_student.populate_table_upladed_students,
        name='populate_table_upladed_students_ajax'
        ),
    path('ajax/populate_table_uploaded_students_2/',
        list_student.populate_table_uploaded_students_2,
        name='populate_table_uploaded_students_2_ajax'
        ),
    path('ajax/populate_summary_panel_students/',
        list_student.populate_summary_panel_ajax,
        name='populate_summary_panel_ajax'
        ),
    path('ajax/populate_hmtl_summary_panel/',
        list_student.populate_hmtl_summary_panel_ajax,
        name='populate_hmtl_summary_panel_ajax'
        ),
    path('ajax/get_filter_options_for_section/',
        list_student.get_filter_options_for_section,
        name='get_filter_options_for_section_ajax'
        ),
    path('ajax/user/populate_table_user_list_ajax/',
        list_user.populate_table_user_list_ajax,
        name='populate_table_user_list_ajax'
        ),
    path('elections/', election.ElectionList.as_view(),name='list_election'),
    path('election/<int:pk>/',
        election.ElectionDetail.as_view(),
        name='detail_election'
        ),
    path('ajax/elections/populate_table_election_list_ajax/',
        election.populate_table_election_list_ajax,
        name='populate_table_election_list_ajax'
        ),
    path('ajax/election/ceate/', election.create_election_ajax,
        name='create_election_ajax'
        ),
    path('ajax/election/update/<int:pk>/',
        election.update_election_ajax,
        name='update_election_ajax'
        ),
    path('ajax/election/toggle_status/<int:pk>/',
        election.toggle_election_status_ajax,
        name='toggle_election_status_ajax'
    ),
    path('ajax/election/more_details/<int:pk>/',
        election.show_more_details_ajax,
        name='election_show_more_details_ajax'
    ),
    path('ajax/election/populate_table_voters_list_ajax/<int:election_id>/',
        election.populate_table_voters_list_ajax,
        name='populate_table_voters_list_ajax'
        ),
    path('ajax/election/generate_batch_token_ajax/<int:election_id>/',
        election.generate_batch_token_ajax,
        name='generate_batch_token_ajax'
        ),
    path('ajax/election/populate_table_voters_summary_ajax/<int:election_id>/',
        election.populate_table_voters_summary_ajax,
        name='populate_table_voters_summary_ajax'
        ),
    path('ajax/election/populate_voters_token_table_ajax/<int:election_id>/',
        election.populate_voters_token_table_ajax,
        name='populate_voters_token_table_ajax'
        ),
    path('ajax/election/complete_election/<int:election_id>/',
        election.complete_election_ajax,
        name='complete_election_ajax'
        ),
    path('positions/', position.PositionList.as_view(), name='position'),
    path('ajax/positions/populate_table_position_list_ajax/',
        position.populate_table_position_list_ajax,
        name='populate_table_position_list_ajax'
    ),
    path('ajax/position/create/', position.create_position_ajax,
        name='create_position_ajax'
    ),
    path('ajax/position/update/<int:pk>/',
        position.update_position_ajax,
        name='update_position_ajax'
    ),
    path('ajax/position/toggle_status/<int:pk>/',
        position.toggle_position_status_ajax,
        name='toggle_position_status_ajax'
    ),
    path('ajax/position/more_details/<int:pk>/',
        position.show_more_details_ajax,
        name='show_more_details_ajax'
    ),
    path('parties/', party.PartyList.as_view(), name='party'),
    path('ajax/parties/populate_table_party_list_ajax/',
        party.populate_table_party_list_ajax,
        name='populate_table_party_list_ajax'
        ),
    path('ajax/party/create/', party.create_ajax,
        name='create_party_ajax'
    ),
    path('ajax/party/update/<int:pk>/',
        party.update_ajax,
        name='update_party_ajax'
    ),
    path('ajax/party/more_details/<int:pk>/',
        party.show_more_details_ajax,
        name='part_more_details_ajax'
    ),
    path('ajax/party/toggle_status/<int:pk>/',
        party.toggle_status_ajax,
        name='party_toggle_status_ajax'
    ),
    path('candidates/', candidate.CandidateList.as_view(), name='candidate'),
    path('ajax/candidates/populate_table_candidate_list_ajax/',
        candidate.populate_table_list_ajax,
        name='populate_table_candidate_list_ajax'
        ),
    path('ajax/candidate/create/', candidate.create_ajax,
        name='create_candidate_ajax'
    ),
    path('ajax/candidate/populate_options_for_student/',
        candidate.populate_options_for_student_ajax,
        name='candidate_populate_options_for_student_ajax'
        ),
    path('ajax/candidate/update/<int:pk>/',
        candidate.update_ajax,
        name='candidate_update_ajax'
    ),
    path('ajax/candidate/toggle_status/<int:pk>/',
        candidate.toggle_status_ajax,
        name='candidate_toggle_status_ajax'
    ),
    path('ajax/candidate/more_details/<int:pk>/',
        candidate.show_more_details_ajax,
        name='candidate_more_details_ajax'
    ),
]

E_Voting/reporting/urls.py
from django.conf.urls import url
from django.urls import path
from reporting.ViewsF import reporting

app_name = 'reporting'

urlpatterns = [
    path('reports/',
        reporting.Reporting.as_view(),
        name='reports'
    ),
    path('ajax/get_votes_distribution/',
        reporting.get_votes_distribution_ajax,
        name='get_votes_distribution_ajax'
    ),
    path('ajax/populate_winner_table/',
        reporting.populate_winner_table_ajax,
        name='populate_winner_table_ajax'
    ),
    path('ajax/populate_result_graphs/',
        reporting.populate_result_graphs_ajax,
        name='populate_result_graphs_ajax'
    ),
    path('ajax/populate_participation_report_graphs_overall/',
        reporting.populate_participation_report_graphs_overall_ajax,
        name='populate_participation_report_graphs_overall_ajax'
    ),
    path('ajax/populate_participation_report_graphs/',
        reporting.populate_participation_report_graphs_ajax,
        name='populate_participation_report_graphs_ajax'
    ),
]

E_Voting/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>DNHS EVS</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- <link href="{% static 'css/bootstrap-toggle.min.css' %}" rel="stylesheet"> -->

      <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- <script src="{% static 'js/popper.min.js' %}"></script> -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block heading %}
    {% endblock %}

  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top navbar-fixed-top navbar-invers">
      <div class="container">
        <ul class="nav navbar-nav">
          <li ><a class="navbar-brand" href="{%url 'home' %}">DNHS E-Voting</a></li>
          <!-- <li><a class="navbar-link" href="">Admin</a></li>
          <li><a class="navbar-link" href="">Other</a></li> -->
          {% if  perms.registration.add_student %}
            <li>
              <div class="dropdown">
                <button class="dropbtn">Student</button>
                <div class="dropdown-content">
                  <a href="{%url 'registration:upload_students' %}">Upload Students</a>
                  <a href="{%url 'registration:add_student' %}">Add Student</a>
                  <!-- <a href="{%url 'registration:list_student' %}">Update Student</a> -->
                    <a href="{%url 'registration:list_student' %}">List of Students</a>
                </div>
              </div>
            </li>
          {% endif %}
          {% if perms.auth.add_user %}
            <li>
              <div class="dropdown">
                <button class="dropbtn">User</button>
                <div class="dropdown-content">
                  <!-- <a href="{#%url 'registration:create_user' %}">Create User</a> -->
                  <!-- <a href="{#%url 'registration:create_election_officer' %}">Create Election Officer</a> -->
                  <a href="{%url 'registration:list_user' %}">User Management</a>
                  <!-- <a href="#">Update Election Officer</a> -->
                  <!-- <a href="#">Link 2</a>
                  <a href="#">Link 3</a> -->
                </div>
              </div>
            </li>
          {% endif %}

        {% if perms.registration.add_election or perms.registration.view_vote %}
          <li>
            <div class="dropdown">
              <button class="dropbtn">Election</button>
              <div class="dropdown-content">
                {% if perms.registration.add_election %}
                <a href="{%url 'registration:position' %}">Position Management</a>
                <a href="{%url 'registration:list_election' %}">Election Management</a>
                <a href="{%url 'registration:party' %}">Party Management</a>
                <a href="{%url 'registration:candidate' %}">Candidate Management</a>
                {% endif %}
                {% if perms.registration.view_vote %}
                <a href="{%url 'election:election_live_monitoring' %}">Live Monitoring</a>
                {% endif %}
                <!-- <a href="#">Review List Voters and Candidates</a>
                <a href="#">Generate Voter's Token</a>
                <a href="#">Add Candidate</a>
                <a href="#">Update Candidate</a>
                <a href="#">Update Candidate Profile</a>
                <a href="#">Create Position</a>
                <a href="#">Update Position</a> -->
              </div>
            </div>
          </li>
        {% endif %}

        {% if perms.registration.view_vote %}
        <li>
          <div class="dropdown">
            <button class="dropbtn">Data Analytics</button>
            <div class="dropdown-content">
              <a href="{%url 'reporting:reports' %}">Reports</a>
            </div>
          </div>
        </li>
        {% endif %}

        </ul>
        <ul class="nav navbar-nav navbar-right">
         <li>
           {% if not user.is_authenticated %}
           <a href="#" class="js-login" data-url="{% url 'login_ajax' %}">
             <span class="glyphicon glyphicon-user"></span>
             Login
           </a>
           {% else %}
           <a href="#" class="js-logout" data-url="{% url 'logout_ajax' %}" redirect-url="{% url 'home' %}">
             <span class="glyphicon glyphicon-log-out"></span>
             Logout({{user}})
           </a>
           {% endif %}
         </li>
         <!-- <li><a href="#"><span class="glyphicon glyphicon-picture"></span> Candidate Profile</a>
         </li> -->
         <li><a href="#" class="js-review-vote" data-url="{% url 'election:review_voters_vote_auth_ajax' %}">
                <span class="glyphicon glyphicon-ok"></span>
                Review Vote
             </a>
         </li>
       </ul>
      </div>
    </nav>

    <div class="container">
      <div class="jumbotron">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <!-- {% if perms.registration.add_election %}
      Student
    {%endif%} -->

    <!-- modal for login -->
    <div class="modal fade" id="modal-login">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

    <!-- modal for review vote authentication-->
    <div class="modal fade" id="modal-review-vote-auth">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

    <!-- modal for review vote after authentication-->
    <div class="modal fade" id="modal-review-vote">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>
<script src="{% static 'base/js/base_1.js' %}"></script>

  {% block javascript %}
  {% endblock %}

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="{%url 'home' %}"> Dakak National High School Electronic Voting System</a>
  </div>
  <!-- Copyright -->


  <!-- <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script> -->
</body>

</html>

E_Voting/templates/base_2.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Voting</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle_2.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- <link href="{% static 'css/bootstrap-toggle.min.css' %}" rel="stylesheet"> -->

      <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- <script src="{% static 'js/popper.min.js' %}"></script> -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block heading %}
    {% endblock %}

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{%url 'home' %}">E-Voting</a>
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse navHeaderCollapse">
            <ul class="nav navbar-nav">
                {% if  perms.registration.add_student %}
                  <li>
                    <div class="dropdown">
                      <button class="dropbtn">Student <b class="caret"></b> </button>
                      <div class="dropdown-content">
                        <a href="{%url 'registration:list_student' %}">List of Students</a>
                        <a href="{%url 'registration:upload_students' %}">Upload Students </a>
                        <a href="{%url 'registration:add_student' %}">Add Student</a>
                      </div>
                    </div>
                  </li>
                {% endif %}
                {% if perms.auth.add_user %}
                  <li>
                    <div class="dropdown">
                      <button class="dropbtn">User <b class="caret"></b>  </button>
                      <div class="dropdown-content">
                        <!-- <a href="{#%url 'registration:create_user' %}">Create User</a> -->
                        <!-- <a href="{#%url 'registration:create_election_officer' %}">Create Election Officer</a> -->
                        <a href="{%url 'registration:list_user' %}">User Management</a>
                        <!-- <a href="#">Update Election Officer</a> -->
                        <!-- <a href="#">Link 2</a>
                        <a href="#">Link 3</a> -->
                      </div>
                    </div>
                  </li>
                {% endif %}

                {% if perms.registration.add_election or perms.registration.view_vote %}
                  <li>
                    <div class="dropdown">
                      <button class="dropbtn">Election <b class="caret"></b> </button>
                      <div class="dropdown-content">
                        <!-- sysadmin can only update position. to prevent manipulation on number of slots -->
                        {% if perms.auth.add_user %}
                        <a href="{%url 'registration:position' %}">Position Management</a>
                        {% endif %}
                        {% if perms.registration.add_election %}
                        <a href="{%url 'registration:list_election' %}">Election Management</a>
                        <a href="{%url 'registration:party' %}">Party Management</a>
                        <a href="{%url 'registration:candidate' %}">Candidate Management</a>
                        {% endif %}
                        {% if perms.registration.view_vote %}
                        <a href="{%url 'election:election_live_monitoring' %}">Live Monitoring</a>
                        {% endif %}
                      </div>
                    </div>
                  </li>
                {% endif %}

                {% if perms.registration.view_vote %}
                <li>
                  <div class="dropdown">
                    <button class="dropbtn">Data Analytics <b class="caret"></b> </button>
                    <div class="dropdown-content">
                      <a href="{%url 'reporting:reports' %}">Reports</a>
                    </div>
                  </div>
                </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
             <li>
               {% if not user.is_authenticated %}
               <a href="#" class="js-login" data-url="{% url 'login_ajax' %}">
                 <span class="glyphicon glyphicon-user"></span>
                 Login
               </a>
               {% else %}
               <a href="#" class="js-logout" data-url="{% url 'logout_ajax' %}" redirect-url="{% url 'home' %}">
                 <span class="glyphicon glyphicon-log-out"></span>
                 Logout({{user}})
               </a>
               {% endif %}
             </li>
             <li><a href="#" class="js-review-vote" data-url="{% url 'election:review_voters_vote_auth_ajax' %}">
                    <span class="glyphicon glyphicon-ok"></span>
                    Review Vote
                 </a>
             </li>
           </ul>
        </div>
      </div>
    </div>

    <div class="container" style="padding-top: 50px; padding-bottom: 50px;">
      <!-- <div class="jumbotron"> -->
        {% block content %}
        {% endblock %}
      <!-- </div> -->
    </div>

    <!-- modal for login -->
    <div class="modal fade" id="modal-login">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

    <!-- modal for review vote authentication-->
    <div class="modal fade" id="modal-review-vote-auth">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

    <!-- modal for review vote after authentication-->
    <div class="modal fade" id="modal-review-vote">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>
<script src="{% static 'base/js/base_1.js' %}"></script>

  {% block javascript %}
  {% endblock %}

  <!-- Copyright -->
  <div class="navbar navbar-default navbar-fixed-bottom navbar-static">
    <div class="container">
      <p>
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
          <a href="{%url 'home' %}"> {{school_name}} Electronic Voting System</a>
        </div>
      </p>
    </div>
  </div>
  <!-- Copyright -->


  <!-- <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script> -->
</body>

</html>

E_Voting/templates/home_page.html
{% extends 'base_2.html' %}
{% load staticfiles %}



{% block content %}
  <h1>Home Page</h1>

  <!-- modal for Voting -->
  <div class="modal  animated" id="modal-section">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>

{% if is_election_day %}

<div class="modal fade" id="modal-vote-confirmation">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" id="modal-ballot">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal animated zoomIn" id="modal-vote-casting-confirmation">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>

<div class="" id="variable_container"
  data-url-authenticate_voter_ajax="{% url 'election:authenticate_voter_ajax' %}"
  >
</div>

  <script type="text/javascript">
    //this will not show on other browser if extracted to other file.js.
    //Try to figure it out if have more time.
    var variable_container = $('#variable_container');

    function animateModal(modal_id, animation) {
      $('#' + modal_id + ' .modal-dialog').attr('class', 'modal-dialog  ' + animation + '  animated');
    };


    $(window).on('load',function(){
      // show modal to authenticate
        $.ajax({
            url: variable_container.attr("data-url-authenticate_voter_ajax"),
            type: 'get',
            dataType: 'json',
            beforeSend: function(){
                // don't close model on click outside of the modal
                          $('#modal-section').modal({backdrop: 'static', keyboard: false});
                          $("#modal-section").modal("show");
                        },
            success: function(data){
                        $("#modal-section .modal-content").html(data.html_form);
                      },
        });
    });

    function show_confirmation(voter_id){
      $.ajax({
        url: "/election/ajax/voter/confirmation/" + voter_id,
        type: 'get',
        dataType: 'json',
        beforeSend: function(){
                      // don't close model on click outside of the modal
                      // $('#modal-vote-confirmation').modal({backdrop: 'static', keyboard: false});
                      // $("#modal-vote-confirmation").modal("show");
                    },
        success: function(data){
           // $("#modal-vote-confirmation .modal-content").html(data.html_form);

           // $("#modal-section .modal-content").html(data.html_form);
            $("#modal-section .modal-content").fadeOut(300, function(){
              $(this).html(data.html_form).fadeIn(300);
            });

           // alert("test");
        }
      });

    }

    $(function () {
      var authenticateVoter = function(){
        var form = $(this);
        $.ajax({
          url: form.attr("action"),
          data: form.serialize(),
          type: form.attr("method"),
          dataType: 'json',
          success: function(data){
            if (data.form_is_valid){
              // convert data.voter string to javascript json format
              var voter = jQuery.parseJSON(data.voter)[0];
              // $("#modal-section").modal("hide");

              //show confirmation page
              show_confirmation(voter.pk);
            }
            else {
              $("#modal-section .modal-content").html(data.html_form);
            }
          }
        });

        //return false to not display the json data value.
        //data should be processed accordingly through ajax's call 'success'
        return false;
      };

      var userConfirmed = function(){
        var btn = $(this);
        $.ajax({
          url: btn.attr("action"),
          type: btn.attr("method"),
          dataType: 'json',
          beforeSend: function(){
                        // $("#modal-vote-confirmation").modal("hide");
                        // don't close model on click outside of the modal
                        // $('#modal-ballot').modal({backdrop: 'static', keyboard: false});
                        // $("#modal-ballot").modal("show");
                      },
          success: function(data){
             // $("#modal-ballot .modal-content").html(data.html_form);
             $("#modal-section").addClass("zoomIn");
             $("#modal-section .modal-content").html(data.html_form);
             // alert("test");
          }
        });

        //return false to not display the json data value.
        //data should be processed accordingly through ajax's call 'success'
        return false;
      };

      var castVote = function(){
        var form = $(this);
        $.ajax({
          url: form.attr("action"),
          data: form.serialize(),
          type: form.attr("method"),
          dataType: 'json',
          success: function(data){
            if (data.form_is_valid){
              //hide #modal-ballot
              // $("#modal-ballot").modal("hide");
              $("#modal-section").addClass("zoomOutUp");

              setTimeout( function() {
                  $("#modal-section").modal("hide");
                  $("#modal-vote-casting-confirmation").modal("show");
                },1300);
              //show confirmation


              //give the voter his/her new token to validate his/her vote
              $("#modal-vote-casting-confirmation .modal-content").html(data.html_form);
            }
            else {
              $("#modal-ballot .modal-content").html(data.html_form);
            }
          }
        });

        //return false to not display the json data value.
        //data should be processed accordingly through ajax's call 'success'
        return false;

      };

      //bind
      $("#modal-section").on("submit", ".js-authenticate-voter-form", authenticateVoter);
      // $('#modal-vote-confirmation').on('click','.js-not-me', function(){
      //     //refresh current page to show again modal-section
      //     //so voter will enter again the token
      //     location.reload();
      // });
      $('#modal-section').on('click','.js-not-me', function(){
          //refresh current page to show again modal-section
          //so voter will enter again the token
          location.reload();
      });
      // $('#modal-vote-confirmation').on("click",".js-this-is-me", userConfirmed);
      $('#modal-section').on("click",".js-this-is-me", userConfirmed);
      $("#modal-section").on("submit", ".js-cast-vote-form", castVote);
      $('#modal-vote-casting-confirmation').on('click','.btn-close', function(){
          //refresh current page to show again modal-section
          //so voter will enter again the token
          location.reload();
      });

      $('#modal-section').on('show.bs.modal', function (e) {
            var animation ='fadeIn';
            animateModal('modal-section', animation);
      });

      // $('#modal-section').on('hide.bs.modal', function (e) {
      //   var animation ='fadeOutRightBig';
      //   animateModal('modal-section', animation);
      // });

    });
  </script>

{% endif %}


{% endblock %}

E_Voting/templates/login.html
{% extends 'base_2.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<div class="jumbotron">
  <h2>Login</h2>
    <form method="post">
      {% csrf_token %}
      {{  form|crispy }}
      <button type="submit">Login</button>
    </form>
  </div>

{% endblock %}