E_Voting/E_Voting/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('ajax/login/', views.LoginViewAjax.as_view(
        template_name='partial_login_ajax.html'),
        name='login_ajax'),
    path('ajax/logout/', views.logout_view_ajax, name='logout_ajax'),
    path('registration/',include('registration.urls',namespace='registration')),
    path('election/',include('election.urls',namespace='election')),
    path('reporting/',include('reporting.urls',namespace='reporting')),
    path('accounts/login/', views.LoginView.as_view(),
        name='login'),
    path('test/',
        views.TestPage.as_view(),
        name='test'
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_Voting/election/urls.py
from django.urls import path
from election.viewsF import vote,live_monitoring

app_name = 'election'

urlpatterns = [
    path('ajax/voter/authenticate/', vote.authenticate_voter_ajax,
        name='authenticate_voter_ajax'
    ),
    path('ajax/voter/confirmation/<int:pk>',
        vote.show_voter_confirmation_ajax,
        name='confirm_voter_ajax'
    ),
    path('ajax/voter/ballot/<int:voter_id>',
        vote.show_voter_ballot_ajax,
        name='voter_ballot_ajax'
    ),
    path('liveVoteMonitoring/',
        live_monitoring.ElectionLiveMonitoring.as_view(),
        name='election_live_monitoring'
    ),
    path('ajax/populate_vote_count/',
        live_monitoring.populate_vote_count_ajax,
        name='populate_vote_count_live'
    ),
    path('ajax/check_for_new_vote/',
        live_monitoring.check_for_new_vote_ajax,
        name='check_for_new_vote_ajax'
    ),
    path('ajax/review_voters_vote_auth/',
        vote.review_voters_vote_auth_ajax,
        name='review_voters_vote_auth_ajax'
    ),
    path('ajax/populate_participation_rate_live/',
        live_monitoring.populate_participation_rate_ajax,
        name='election_live_populate_participation_rate'
    ),
    ]

E_Voting/election/models.py
from django.db import models
from registration import models as RegistrationModels
from django.conf import settings
from election.management.helpers.hasher_helpers import MyHasher
import uuid

# Create your models here.
class Ballot(RegistrationModels.BaseModel):
    vote_casted_timestamp = models.DateTimeField(null=False)
    # https://stackoverflow.com/questions/4581789/how-do-i-get-user-ip-address-in-django
    # request.META.get('REMOTE_ADDR')
    vote_casting_IP = models.GenericIPAddressField(null=True)
    voter_id_h = models.CharField(
            max_length=255,
            verbose_name="Hashed Voter ID",
            null=False,
            default=uuid.uuid4().hex,
            unique=True,
    )

    def assign_voter_id(self, voter):
        self.voter_id_h = voter.hash_id

E_Voting/election/forms.py
from django import forms
from registration.models import Voter,Candidate
from registration.models import Position
from django.contrib.auth.models import Group  #testing only, remove after testing

class VoterAuthenticateForm(forms.Form):
    token = forms.CharField()
    election = None
    # to minimized database hits, get the voter from this form and views will get it from here
    voter =  None

    def __init__(self, *args, **kwargs):
        if kwargs.get('election',None):
            self.election = kwargs.get('election')
            #after getting the data, delete passed argument to prevent error on calling super().__init__()
            del kwargs['election']
        super().__init__(*args, **kwargs)
        self.fields['token'].label = "Enter your TOKEN to cast your vote!"

    def clean_token(self):
        cleaned_data = super().clean()
        token = cleaned_data['token'].upper() # convert input to upper
        #check if token on Voter model exist based on the current election
        voter_ = Voter.objects.filter(voter_token=token, election=self.election).first()
        if not voter_:
            raise forms.ValidationError(
                "This is not a valid token for this election. Kindly check."
            )
        else:
            # check if the voter voted already
            if voter_.is_vote_casted:
                raise forms.ValidationError(
                    "This token has been used already!"
                )
            else:
                self.voter = voter_
                return token

class VoterConfirmationForm(forms.ModelForm):
    voter_token = forms.CharField(required=False)
    voter_name = forms.CharField(required=False)
    voter_class = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['voter_name'].initial = self.instance.student.name_title
            self.fields['voter_class'].initial = "{} - {}".format(
                                self.instance.student_class.grade_level,
                                self.instance.student_class.section
            )

        for key in self.fields.items(): #set all field as disabled
            self.fields[key[0]].widget.attrs['disabled'] = True
        self.fields['voter_name'].label = "Your Name"
        self.fields['voter_token'].label = "Your Token"
        self.fields['voter_class'].label = "Your Class"


    class Meta:
        model = Voter
        fields = ('voter_token',)

class OfficialBallotForm(forms.Form):
    '''
        official ballot of the voter.
        Dynamic number of fields based on the number of positions of the current election
    '''
    voter = None

    def __init__(self, *args, **kwargs):
        if kwargs.get('voter', None):
            self.voter = kwargs.get('voter')
            #after getting the data, delete passed argument to prevent error on calling super().__init__()
            del kwargs['voter']
        super().__init__(*args, **kwargs)
        # get first the candidates of this voter
        candidates = Candidate.objects.get_candidate_of_voter(
                        self.voter.election,
                        self.voter.student_class.grade_level
                    )
        # get this value in the view
        self.candidate_list = candidates
        # based on the list of candidates, get the positions available
        positions = [
                candidate.position.__str__() for candidate in  candidates
                ]
        for position in positions:
            field_name = position
            number_of_slots = Position.objects.get(title=position).number_of_slots
            # get the candidates for every position
            candidates_for_this_position = tuple([
                (candidate.pk, candidate.student.__str__()) \
                for candidate in candidates.filter(position__title=position)
                        ])
            self.fields[field_name] = forms.MultipleChoiceField(
                                widget=forms.CheckboxSelectMultiple(
                                        attrs = { #variable place holder that will be consumed on the template
                                            # this will determine how many allowed candidate per position
                                            'number-of-slots': number_of_slots,
                                             #this will identify the last element checked. Based on this number and number_of_slots,
                                             #other elements will be automatically unchecked
                                            'last-checked-counter': 0,
                                            'hook-value': 'candidate',
                                        },
                                    ),
                                choices=candidates_for_this_position,
                                required=False
                            )
            self.fields[field_name].label = "{}(Choose {} only)".format(field_name,number_of_slots)

    def clean(self):
        cleaned_data = super().clean()
        for position,value in self.cleaned_data.items():
            if len(value) > Position.objects.get(title=position).number_of_slots:
                raise forms.ValidationError(
                    "Number of votes is more than the specified number of slots for {} position.".format(
                        position
                    )
                )

class VoterReviewVoteAuthenticate(forms.Form):
    token = forms.CharField()
    secret_password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['token'].label = "Enter your TOKEN:"
        self.fields['secret_password'].label = "Enter your secret password:"
        self.voter = None

    def clean_token(self):
        cleaned_data = super().clean()
        token = cleaned_data['token'].upper()
        # use select related to cache the objects from election model
        # will be used later on the view
        self.voter = Voter.objects.select_related('election').filter(
                        voter_token=token
                        ).first()
        if not self.voter:
            raise forms.ValidationError(
                "This is not a valid token. Kindly check."
            )
        else:
            return token

    def clean_secret_password(self):
        cleaned_data = super().clean()
        secret_password = cleaned_data['secret_password']
        if self.voter:
            if not self.voter.authenticate_for_vote_validation(secret_password):
                raise forms.ValidationError(
                    "Invalid secret password."
                )
            else:
                return secret_password
        else:
            return secret_password

E_Voting/election/views.py
from django.shortcuts import render

# Create your views here.

E_Voting/election/templates/election/partial_cast_vote_modal.html
<!-- Voting should be done in here -->
<!--  Find a way to not close this model unless closed by user -->

{% load widget_tweaks %}
{% load staticfiles %}
{% load crispy_forms_tags %}


<form method="post"
    action="{% url 'election:authenticate_voter_ajax' %}"
    class="js-cast-vote-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-lable="Close"">
      <span area-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">
      Welcome to {{ object.name|title }} Election of School Year {{ object.school_year }}
    </h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group {% if field.errors %} has-error {% endif%}">
        {% for error in field.errors %}
          <p class="help-block"> {{ error }}</p>
        {% endfor %}
        {{ field|as_crispy_field }}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">
          <!-- <span class="glyphicon glyphicon-circle-arrow-right"></span> -->
          <span class="spinner-border spinner-border-sm"></span>
              Enters
        </button>
  </div>
</form>

E_Voting/election/templates/election/partial_vote_casting_confirmation.html
<!-- this modal whill be shown after voter cast the vote -->
<!-- New token will be shown here so user can validate the vote after -->
<!-- This model should not be closed unless confrimation is clicked -->

{% load widget_tweaks %}
{% load crispy_forms_tags %}


<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-lable="Close"">
    <span area-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title">
    Hi {{object.student.first_name|title}}, your vote has been counted!
  </h4>
</div>
<div class="modal-body">
  Please right-down your <b>secret</b> password to view your vote!
  <p>{{voter_validation_token}}</p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default btn-close" data-dismiss="modal">Close</button>
  <button type="submit" class="btn btn-primary btn-close">
      Done
  </button>
</div>

E_Voting/election/templates/election/partial_voter_ballot.html
<!-- this modal whill be shown after voter confirmed -->
<!-- This serves as the voter's ballot and this is the page where the voter cast his vote -->
<!-- This model should not be closed unless confrimation is clicked -->
{% load staticfiles %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<script src="{% static 'js/popper.min.js' %}"></script>

<form method="post"
    action="{% url 'election:voter_ballot_ajax' object.pk %}"
    class="js-cast-vote-form">
  {% csrf_token %}

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-lable="Close"">
      <span area-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Hi {{object.student.first_name|title}}, here is your OFFICIAL BALLOT!</h4>
  </div>

  <div class="modal-body">
    {% for field in form %}
      <div class="form-group {% if field.errors %} has-error {% endif%}">
        {% for error in field.errors %}
          <p class="help-block"> {{ error }}</p>
        {% endfor %}

        {{ field|as_crispy_field }}
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal" style="display: inline-block;">Close</button>
    <button id="cast-vote-btn" type="submit" class="btn btn-primary" style="display: inline-block;" disabled>
        <span class="glyphicon glyphicon-send"></span>
        Cast Vote
    </button>
    <div class="checkbox" style="display: inline-block;">
          <label>
            <input type="checkbox" id="vote-confirmation-checkbox"><b>Confirm Votes</b>
          </label>
    </div>
  </div>
</form>

{% for candidate in candidates %}

  <script type="text/javascript">
    $(document).ready( function () {
        var candidate_label = $('[value=' + {{candidate.id}} + ']').parent();
        var title_text = "<img class='img-responsive img-thumbnail' src='/media/{{candidate.profile_pic}}'/>";
        // title_text = "<img class='img-thumbnail' src='https://picsum.photos/200/100'/>sadfsadfssdf";
        candidate_label.attr('data-toggle', 'tooltip');
        candidate_label.attr('data-original-title', title_text);
        candidate_label.attr('title','');
        candidate_label.attr('data-placement','right');
        candidate_label.append("(" + "{{candidate.party.display_name}}" + ")");
        candidate_label.css("font-size","120%");
      });

      //remove white spaces on IDs especially those for representatives
      //this is to fix automatic uncheck feature depending of position's
      //number of slots
      var attr_id = $('[value=' + {{candidate.id}} + ']').attr('id');
      //replace space with underscore
      attr_id_replaced = attr_id.replace(/\s/g,'_');
      $('[value=' + {{candidate.id}} + ']').attr('id',attr_id_replaced);


  </script>


{% endfor %}

<script type="text/javascript">
  $(function() {
    $('[data-toggle="tooltip"]').tooltip({
        html: true
      });
  });

  $(function(){

    $('#vote-confirmation-checkbox').change( function(){
        if($(this).is(':checked')){
            console.log($('#cast-vote-btn').attr('disabled'));
            $('#cast-vote-btn').attr('disabled', false);
        }
        else{
          console.log($('#cast-vote-btn').attr('disabled'));
          $('#cast-vote-btn').attr('disabled', true);
        }
    });

    //get all form-check-label class and rename the ID. remove spaces.
    //this is to work check/uncheck of checkbox if lable is checked.
    //feature was disabled due to renaming of ID above inside for loop
    $('.form-check-label').each(function(index, value){
        var for_old = $(this).attr('for');
        var for_new = for_old.replace(/\s/g,'_'); //remove space with _
        $(this).attr('for', for_new);
    });

    //listener
    // grab all checkbox inputs
    //add some logic to auto uncheck based on the number of slots
    $('input:checkbox').change( function() {
      var number_of_slots = parseInt($(this).attr("number-of-slots"));

      //track last checked
      if($(this).is(':checked')){

        //find the max last-checked-counter
        max_checked_counter = 0;
        $(this).parent().parent().siblings()
                .find('input:checkbox:checked')
                .each( function(index, value) {
                  if (parseInt($(this).attr("last-checked-counter")) > max_checked_counter){
                    max_checked_counter = parseInt($(this).attr("last-checked-counter"));
                  }
                });

        $(this).attr("last-checked-counter",max_checked_counter + 1); //set to track as this is the latest checked element

        //get other checkboxes
        //get count of checked checkboxes
        //find the least recent checked element to tbe unchecked
        var siblings_checked_count = 0;
        var least_counter;
        var least_checked_id;
        $(this).parent().parent().siblings()
                .find('input:checkbox:checked')
                .each( function(index, value) {

                    // find the least element to be unchecked
                    if (least_counter === undefined) {
                      least_counter = parseInt($(this).attr("last-checked-counter"));
                      least_checked_id = $(this).attr("id");
                    }
                    else {
                      if (parseInt($(this).attr("last-checked-counter")) < least_counter) {
                        least_counter = parseInt($(this).attr("last-checked-counter"));
                        least_checked_id = $(this).attr("id");
                      }
                    }
                    siblings_checked_count += 1;

                });

        if (siblings_checked_count >= number_of_slots){
          //unchecked the least recent candidate
          $('#' + least_checked_id).prop('checked', false);

        }

      }
      else { //reset to 0
        last_checked_counter = 0; //reset
        $(this).attr("last-checked-counter",last_checked_counter); //then set again
      }

    });

  });


</script>

E_Voting/election/templates/election/partial_voter_ballot_to_remove.html
<!-- this modal whill be shown after voter confirmed -->
<!-- This serves as the voter's ballot and this is the page where the voter cast his vote -->
<!-- This model should not be closed unless confrimation is clicked -->

{% load widget_tweaks %}
{% load staticfiles %}
{% load crispy_forms_tags %}

<div class="modal-header">
  <h4 class="modal-title">{{object.student.first_name|title}}, this is your OFFICIAL BALLOT!</h4>
</div>
<div class="modal-body">
  {% for position in positions_with_candidate %}
      <div class="form-group">
        <label>{{position.position}} ({{position.number_of_slots}})</label>
          <div id="id_{{position.position}}">
            {% for candidate in position.candidates %}
              <div class="checkbox">
                  <label for="id_{{position.position}}_{{candidate.counter}}">
                    <input type="checkbox" name="{{position.position}}" value="{{candidate.candidate_id}}"
                      id="id_{{position.position}}_{{candidate.counter}}">
                   {{ candidate.candidate_name }}
                  </label>
                </div>
            {% endfor %}
          </div>
      </div>
  {% endfor%}
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <button type="submit" class="btn btn-primary">
      <span class="glyphicon glyphicon-send"></span>
      Cast Vote
  </button>
</div>

E_Voting/election/templates/election/partial_voter_confirm.html
<!-- this modal whill be shown after voter authenticated -->
<!-- It will show voter information, and click confirm to proceed casting votes -->

{% load widget_tweaks %}
{% load crispy_forms_tags %}

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-lable="Close"">
    <span area-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title">
    Hi {{object.student.first_name|title}}, please confirm your information below!
  </h4>
</div>
<div class="modal-body">
  {% for field in form %}
    <div class="form-group {% if field.errors %} has-error {% endif%}">
      {% for error in field.errors %}
        <p class="help-block"> {{ error }}</p>
      {% endfor %}
      {{ field|as_crispy_field }}
    </div>
  {% endfor %}
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-danger js-not-me " data-dismiss="modal">
    <span class="glyphicon glyphicon-remove-circle"></span>
      This is NOT Me
  </button>
  <button type="button" class="btn btn-success js-this-is-me" method="get"
    action="{% url 'election:voter_ballot_ajax' object.pk %}"
    >
      <span class="glyphicon glyphicon-ok-circle"></span>
          This is me
    </button>
</div>

E_Voting/election/templates/election/partial_voters_login_modal.html
{% load widget_tweaks %}
{% load staticfiles %}
{% load crispy_forms_tags %}

<form method="post"
    action="{% url 'election:authenticate_voter_ajax' %}"
    class="js-authenticate-voter-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-lable="Close"">
      <span area-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">
      Welcome to {{ object.name|title }} Election for School Year {{ object.school_year }}
    </h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group {% if field.errors %} has-error {% endif%}">
        {% for error in field.errors %}
          <p class="help-block"> {{ error }}</p>
        {% endfor %}
        {{ field|as_crispy_field }}
      </div>
    {% endfor %}
  </div>  
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">
          <span class="glyphicon glyphicon-circle-arrow-right"></span>
              Enter
      </button>

  </div>
</form>

<script> //initialize script

    $(document).ready( function () {
      $('#id_token').keyup(function() {
        $(this).val($(this).val().toUpperCase());
      });
    });
</script>

E_Voting/election/templates/election/partial_voters_review_vote.html
{% load widget_tweaks %}
{% load staticfiles %}
{% load crispy_forms_tags %}

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-lable="Close"">
      <span area-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">
      Hi {{voter|title}}, these are your votes!
    </h4>
  </div>
  <div class="modal-body">
    <div class="table-responsive">
      <table class="table table-hover display">
        <thead class='thead-dark'>
            <tr>
              <th>Position</th>
              <th>Candidate</th>
            </tr>
          </thead>
          <tbody>
          {% for vote in votes %}
            <tr>
              <td>{{vote.position}}</td>
              <td>{{vote.candidate}}</td>
            </tr>
          {% endfor %}
        </tbody>        
      </table>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>

E_Voting/election/templates/election/partial_voters_review_vote_auth.html
{% load widget_tweaks %}
{% load staticfiles %}
{% load crispy_forms_tags %}

<form method="post"
    action="{% url 'election:review_voters_vote_auth_ajax' %}"
    class="js-review-vote-auth-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-lable="Close"">
      <span area-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">
      Review your vote.
    </h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group {% if field.errors %} has-error {% endif%}">
        {% for error in field.errors %}
          <p class="help-block"> {{ error }}</p>
        {% endfor %}
        {{ field|as_crispy_field }}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">
          <span class="glyphicon glyphicon-circle-arrow-right"></span>
              Enter
      </button>

  </div>
</form>

<script> //initialize script

    $(document).ready( function () {
      $('#id_token').keyup(function() {
        $(this).val($(this).val().toUpperCase());
      });
    });
</script>

E_Voting/election/templates/election/temp.html
<ul>
  {% for position in positions_with_candidate %}
    <li>{{position.position}} ({{position.number_of_slots}})</li>
    <ul>
      {% for candidate in position.candidates %}
        <li>{{ candidate }}</li>
      {% endfor %}
    </ul>
  {% endfor%}
</ul>


  <script src="{% static 'base/js/election_day.js' %}"></script>